/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.17.2.0 (NJsonSchema v9.10.45.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import "rxjs/add/observable/fromPromise";
import "rxjs/add/observable/of";
import "rxjs/add/observable/throw";
import "rxjs/add/operator/map";
import "rxjs/add/operator/toPromise";
import "rxjs/add/operator/mergeMap";
import "rxjs/add/operator/catch";

import { Observable } from "rxjs/Observable";
import { Injectable, Inject, Optional, InjectionToken } from "@angular/core";
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpResponseBase,
  HttpErrorResponse
} from "@angular/common/http";

export const API_BASE_URL = new InjectionToken("API_BASE_URL");

export interface IProjectsClient {
  getProjects(filter: ProjectFilter): Observable<Project[] | null>;
  createProject(model: CreateProjectModel | null): Observable<object | null>;
  getProjectById(id: string): Observable<Project | null>;
  put(id: string, model: UpdateProjectModel | null): Observable<object | null>;
  delete(id: string): Observable<object | null>;
}

@Injectable()
export class ProjectsClient implements IProjectsClient {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver:
    | ((key: string, value: any) => any)
    | undefined = undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional()
    @Inject(API_BASE_URL)
    baseUrl?: string
  ) {
    this.http = http;
    this.baseUrl = baseUrl ? baseUrl : "";
  }

  getProjects(filter: ProjectFilter): Observable<Project[] | null> {
    let url_ = this.baseUrl + "/api/Projects?";
    if (filter.name !== undefined)
      url_ += "Name=" + encodeURIComponent("" + filter.name) + "&";
    if (filter.description !== undefined)
      url_ +=
        "Description=" + encodeURIComponent("" + filter.description) + "&";
    if (filter.status !== undefined)
      url_ += "Status=" + encodeURIComponent("" + filter.status) + "&";
    url_ = url_.replace(/[?&]$/, "");

    return this.http.get(url_).map(x => {
      return <Project[]>x;
    });
  }

  createProject(model: CreateProjectModel | null): Observable<object | null> {
    let url_ = this.baseUrl + "/api/Projects";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(model);

    return this.http.post(url_, content_);
  }

  getProjectById(id: string): Observable<Project | null> {
    let url_ = this.baseUrl + "/api/Projects/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    return this.http.get(url_).map(x => {
      return <Project>x;
    });
  }

  put(id: string, model: UpdateProjectModel | null): Observable<object | null> {
    let url_ = this.baseUrl + "/api/Projects/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(model);

    return this.http.put(url_, content_);
  }

  delete(id: string): Observable<object | null> {
    let url_ = this.baseUrl + "/api/Projects/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    return this.http.delete(url_);
  }
}

export enum ProjectStatus {
  Active = "Active",
  Inactive = "Inactive"
}

export class CreateProjectModel implements ICreateProjectModel {
  name?: string | undefined;
  description?: string | undefined;
  status: ProjectStatus;

  constructor(data?: ICreateProjectModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(data?: any) {
    if (data) {
      this.name = data["Name"];
      this.description = data["Description"];
      this.status = data["Status"];
    }
  }

  static fromJS(data: any): CreateProjectModel {
    data = typeof data === "object" ? data : {};
    let result = new CreateProjectModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Name"] = this.name;
    data["Description"] = this.description;
    data["Status"] = this.status;
    return data;
  }
}

export interface ICreateProjectModel {
  name?: string | undefined;
  description?: string | undefined;
  status: ProjectStatus;
}

export class UpdateProjectModel implements IUpdateProjectModel {
  name?: string | undefined;
  description?: string | undefined;
  status: ProjectStatus;

  constructor(data?: IUpdateProjectModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(data?: any) {
    if (data) {
      this.name = data["Name"];
      this.description = data["Description"];
      this.status = data["Status"];
    }
  }

  static fromJS(data: any): UpdateProjectModel {
    data = typeof data === "object" ? data : {};
    let result = new UpdateProjectModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Name"] = this.name;
    data["Description"] = this.description;
    data["Status"] = this.status;
    return data;
  }
}

export interface IUpdateProjectModel {
  name?: string | undefined;
  description?: string | undefined;
  status: ProjectStatus;
}

export class Project {
  id: string;
  name: string;
  description: string;
  status: ProjectStatus;
}

export class ProjectFilter {
  name: string | null | undefined;
  description: string | null | undefined;
  status: ProjectStatus | null | undefined;
}
