/* tslint:disable */
//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v11.17.3.0 (NJsonSchema v9.10.46.0 (Newtonsoft.Json v9.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------
// ReSharper disable InconsistentNaming

import "rxjs/add/observable/fromPromise";
import "rxjs/add/observable/of";
import "rxjs/add/observable/throw";
import "rxjs/add/operator/map";
import "rxjs/add/operator/toPromise";
import "rxjs/add/operator/mergeMap";
import "rxjs/add/operator/catch";

import { Observable } from "rxjs/Observable";
import { Injectable, Inject, Optional, InjectionToken } from "@angular/core";
import {
  HttpClient,
  HttpHeaders,
  HttpParams,
  HttpResponse,
  HttpResponseBase,
  HttpErrorResponse
} from "@angular/common/http";
import { API_BASE_URL } from "../globals";

export interface IProjectTasksClient {
  getByFilter(
    name: string | null | undefined,
    description: string | null | undefined,
    number: string | null | undefined,
    reporterId: string | null | undefined,
    assigneeId: string | null | undefined,
    createdDate: Date | null | undefined,
    dueDate: Date | null | undefined,
    completedDate: Date | null | undefined,
    status: ProjectTaskStatus | null | undefined,
    projectId: string | null | undefined
  ): Observable<ProjectTaskModel[] | null>;
  create(model: CreateProjectTaskModel | null): Observable<void>;
  getById(id: string): Observable<ProjectTaskModel | null>;
  update(id: string, model: UpdateProjectTaskModel | null): Observable<void>;
  delete(id: string): Observable<void>;
}

@Injectable()
export class ProjectTasksClient implements IProjectTasksClient {
  private http: HttpClient;
  private baseUrl: string;
  protected jsonParseReviver:
    | ((key: string, value: any) => any)
    | undefined = undefined;

  constructor(
    @Inject(HttpClient) http: HttpClient,
    @Optional()
    @Inject(API_BASE_URL)
    baseUrl?: string
  ) {
    this.http = http;
    this.baseUrl = baseUrl ? baseUrl : "";
  }

  getByFilter(
    name: string | null | undefined,
    description: string | null | undefined,
    number: string | null | undefined,
    reporterId: string | null | undefined,
    assigneeId: string | null | undefined,
    createdDate: Date | null | undefined,
    dueDate: Date | null | undefined,
    completedDate: Date | null | undefined,
    status: ProjectTaskStatus | null | undefined,
    projectId: string | null | undefined
  ): Observable<ProjectTaskModel[] | null> {
    let url_ = this.baseUrl + "/api/ProjectTasks?";
    if (name !== undefined)
      url_ += "Name=" + encodeURIComponent("" + name) + "&";
    if (description !== undefined)
      url_ += "Description=" + encodeURIComponent("" + description) + "&";
    if (number !== undefined)
      url_ += "Number=" + encodeURIComponent("" + number) + "&";
    if (reporterId !== undefined)
      url_ += "ReporterId=" + encodeURIComponent("" + reporterId) + "&";
    if (assigneeId !== undefined)
      url_ += "AssigneeId=" + encodeURIComponent("" + assigneeId) + "&";
    if (createdDate !== undefined)
      url_ +=
        "CreatedDate=" +
        encodeURIComponent(createdDate ? "" + createdDate.toJSON() : "") +
        "&";
    if (dueDate !== undefined)
      url_ +=
        "DueDate=" +
        encodeURIComponent(dueDate ? "" + dueDate.toJSON() : "") +
        "&";
    if (completedDate !== undefined)
      url_ +=
        "CompletedDate=" +
        encodeURIComponent(completedDate ? "" + completedDate.toJSON() : "") +
        "&";
    if (status !== undefined)
      url_ += "Status=" + encodeURIComponent("" + status) + "&";
    if (projectId !== undefined)
      url_ += "ProjectId=" + encodeURIComponent("" + projectId) + "&";
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json",
        Accept: "application/json"
      })
    };

    return this.http
      .request("get", url_, options_)
      .flatMap((response_: any) => {
        return this.processGetByFilter(response_);
      })
      .catch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processGetByFilter(<any>response_);
          } catch (e) {
            return <Observable<
              ProjectTaskModel[] | null
            >>(<any>Observable.throw(e));
          }
        } else
          return <Observable<ProjectTaskModel[] | null>>(<any>Observable.throw(
            response_
          ));
      });
  }

  protected processGetByFilter(
    response: HttpResponseBase
  ): Observable<ProjectTaskModel[] | null> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (<any>response).error instanceof Blob
          ? (<any>response).error
          : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).flatMap(_responseText => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        if (resultData200 && resultData200.constructor === Array) {
          result200 = [];
          for (let item of resultData200)
            result200.push(ProjectTaskModel.fromJS(item));
        }
        return Observable.of(result200);
      });
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    }
    return Observable.of<ProjectTaskModel[] | null>(<any>null);
  }

  create(model: CreateProjectTaskModel | null): Observable<void> {
    let url_ = this.baseUrl + "/api/ProjectTasks";
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(model);

    let options_: any = {
      body: content_,
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json"
      })
    };

    return this.http
      .request("post", url_, options_)
      .flatMap((response_: any) => {
        return this.processCreate(response_);
      })
      .catch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processCreate(<any>response_);
          } catch (e) {
            return <Observable<void>>(<any>Observable.throw(e));
          }
        } else return <Observable<void>>(<any>Observable.throw(response_));
      });
  }

  protected processCreate(response: HttpResponseBase): Observable<void> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (<any>response).error instanceof Blob
          ? (<any>response).error
          : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 201) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return Observable.of<void>(<any>null);
      });
    } else if (status === 400) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "A server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    }
    return Observable.of<void>(<any>null);
  }

  getById(id: string): Observable<ProjectTaskModel | null> {
    let url_ = this.baseUrl + "/api/ProjectTasks/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json",
        Accept: "application/json"
      })
    };

    return this.http
      .request("get", url_, options_)
      .flatMap((response_: any) => {
        return this.processGetById(response_);
      })
      .catch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processGetById(<any>response_);
          } catch (e) {
            return <Observable<ProjectTaskModel | null>>(<any>Observable.throw(
              e
            ));
          }
        } else
          return <Observable<ProjectTaskModel | null>>(<any>Observable.throw(
            response_
          ));
      });
  }

  protected processGetById(
    response: HttpResponseBase
  ): Observable<ProjectTaskModel | null> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (<any>response).error instanceof Blob
          ? (<any>response).error
          : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 200) {
      return blobToText(responseBlob).flatMap(_responseText => {
        let result200: any = null;
        let resultData200 =
          _responseText === ""
            ? null
            : JSON.parse(_responseText, this.jsonParseReviver);
        result200 = resultData200
          ? ProjectTaskModel.fromJS(resultData200)
          : <any>null;
        return Observable.of(result200);
      });
    } else if (status === 404) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "A server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    }
    return Observable.of<ProjectTaskModel | null>(<any>null);
  }

  update(id: string, model: UpdateProjectTaskModel | null): Observable<void> {
    let url_ = this.baseUrl + "/api/ProjectTasks/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    const content_ = JSON.stringify(model);

    let options_: any = {
      body: content_,
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json"
      })
    };

    return this.http
      .request("put", url_, options_)
      .flatMap((response_: any) => {
        return this.processUpdate(response_);
      })
      .catch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processUpdate(<any>response_);
          } catch (e) {
            return <Observable<void>>(<any>Observable.throw(e));
          }
        } else return <Observable<void>>(<any>Observable.throw(response_));
      });
  }

  protected processUpdate(response: HttpResponseBase): Observable<void> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (<any>response).error instanceof Blob
          ? (<any>response).error
          : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return Observable.of<void>(<any>null);
      });
    } else if (status === 400) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "A server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    } else if (status === 404) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "A server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    }
    return Observable.of<void>(<any>null);
  }

  delete(id: string): Observable<void> {
    let url_ = this.baseUrl + "/api/ProjectTasks/{id}";
    if (id === undefined || id === null)
      throw new Error("The parameter 'id' must be defined.");
    url_ = url_.replace("{id}", encodeURIComponent("" + id));
    url_ = url_.replace(/[?&]$/, "");

    let options_: any = {
      observe: "response",
      responseType: "blob",
      headers: new HttpHeaders({
        "Content-Type": "application/json"
      })
    };

    return this.http
      .request("delete", url_, options_)
      .flatMap((response_: any) => {
        return this.processDelete(response_);
      })
      .catch((response_: any) => {
        if (response_ instanceof HttpResponseBase) {
          try {
            return this.processDelete(<any>response_);
          } catch (e) {
            return <Observable<void>>(<any>Observable.throw(e));
          }
        } else return <Observable<void>>(<any>Observable.throw(response_));
      });
  }

  protected processDelete(response: HttpResponseBase): Observable<void> {
    const status = response.status;
    const responseBlob =
      response instanceof HttpResponse
        ? response.body
        : (<any>response).error instanceof Blob
          ? (<any>response).error
          : undefined;

    let _headers: any = {};
    if (response.headers) {
      for (let key of response.headers.keys()) {
        _headers[key] = response.headers.get(key);
      }
    }
    if (status === 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return Observable.of<void>(<any>null);
      });
    } else if (status === 404) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "A server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    } else if (status !== 200 && status !== 204) {
      return blobToText(responseBlob).flatMap(_responseText => {
        return throwException(
          "An unexpected server error occurred.",
          status,
          _responseText,
          _headers
        );
      });
    }
    return Observable.of<void>(<any>null);
  }
}

export enum ProjectTaskStatus {
  ToDo = "ToDo",
  InProgress = "InProgress",
  Done = "Done"
}

export class ProjectTaskModel implements IProjectTaskModel {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  number?: string | undefined;
  reporterId: string;
  assigneeId: string;
  createdDate: Date;
  dueDate?: Date | undefined;
  completedDate?: Date | undefined;
  status: ProjectTaskStatus;
  projectId: string;

  constructor(data?: IProjectTaskModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(data?: any) {
    if (data) {
      this.id = data["id"];
      this.name = data["name"];
      this.description = data["description"];
      this.number = data["number"];
      this.reporterId = data["reporterId"];
      this.assigneeId = data["assigneeId"];
      this.createdDate = data["createdDate"]
        ? new Date(data["createdDate"].toString())
        : <any>undefined;
      this.dueDate = data["dueDate"]
        ? new Date(data["dueDate"].toString())
        : <any>undefined;
      this.completedDate = data["completedDate"]
        ? new Date(data["completedDate"].toString())
        : <any>undefined;
      this.status = data["status"];
      this.projectId = data["projectId"];
    }
  }

  static fromJS(data: any): ProjectTaskModel {
    data = typeof data === "object" ? data : {};
    let result = new ProjectTaskModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["id"] = this.id;
    data["name"] = this.name;
    data["description"] = this.description;
    data["number"] = this.number;
    data["reporterId"] = this.reporterId;
    data["assigneeId"] = this.assigneeId;
    data["createdDate"] = this.createdDate
      ? this.createdDate.toISOString()
      : <any>undefined;
    data["dueDate"] = this.dueDate
      ? this.dueDate.toISOString()
      : <any>undefined;
    data["completedDate"] = this.completedDate
      ? this.completedDate.toISOString()
      : <any>undefined;
    data["status"] = this.status;
    data["projectId"] = this.projectId;
    return data;
  }
}

export interface IProjectTaskModel {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  number?: string | undefined;
  reporterId: string;
  assigneeId: string;
  createdDate: Date;
  dueDate?: Date | undefined;
  completedDate?: Date | undefined;
  status: ProjectTaskStatus;
  projectId: string;
}

export class CreateProjectTaskModel implements ICreateProjectTaskModel {
  name: string;
  description: string;
  number: string;
  reporterId: string;
  assigneeId: string;
  createdDate: Date;
  dueDate?: Date | undefined;
  completedDate?: Date | undefined;
  status: ProjectTaskStatus;
  projectId: string;

  constructor(data?: ICreateProjectTaskModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(data?: any) {
    if (data) {
      this.name = data["Name"];
      this.description = data["Description"];
      this.number = data["Number"];
      this.reporterId = data["ReporterId"];
      this.assigneeId = data["AssigneeId"];
      this.createdDate = data["CreatedDate"]
        ? new Date(data["CreatedDate"].toString())
        : <any>undefined;
      this.dueDate = data["DueDate"]
        ? new Date(data["DueDate"].toString())
        : <any>undefined;
      this.completedDate = data["CompletedDate"]
        ? new Date(data["CompletedDate"].toString())
        : <any>undefined;
      this.status = data["Status"];
      this.projectId = data["ProjectId"];
    }
  }

  static fromJS(data: any): CreateProjectTaskModel {
    data = typeof data === "object" ? data : {};
    let result = new CreateProjectTaskModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Name"] = this.name;
    data["Description"] = this.description;
    data["Number"] = this.number;
    data["ReporterId"] = this.reporterId;
    data["AssigneeId"] = this.assigneeId;
    data["CreatedDate"] = this.createdDate
      ? this.createdDate.toISOString()
      : <any>undefined;
    data["DueDate"] = this.dueDate
      ? this.dueDate.toISOString()
      : <any>undefined;
    data["CompletedDate"] = this.completedDate
      ? this.completedDate.toISOString()
      : <any>undefined;
    data["Status"] = this.status;
    data["ProjectId"] = this.projectId;
    return data;
  }
}

export interface ICreateProjectTaskModel {
  name: string;
  description: string;
  number: string;
  reporterId: string;
  assigneeId: string;
  createdDate: Date;
  dueDate?: Date | undefined;
  completedDate?: Date | undefined;
  status: ProjectTaskStatus;
  projectId: string;
}

export class UpdateProjectTaskModel implements IUpdateProjectTaskModel {
  name: string;
  description: string;
  number: string;
  assigneeId: string;
  dueDate?: Date | undefined;
  completedDate?: Date | undefined;
  status: ProjectTaskStatus;

  constructor(data?: IUpdateProjectTaskModel) {
    if (data) {
      for (var property in data) {
        if (data.hasOwnProperty(property))
          (<any>this)[property] = (<any>data)[property];
      }
    }
  }

  init(data?: any) {
    if (data) {
      this.name = data["Name"];
      this.description = data["Description"];
      this.number = data["Number"];
      this.assigneeId = data["AssigneeId"];
      this.dueDate = data["DueDate"]
        ? new Date(data["DueDate"].toString())
        : <any>undefined;
      this.completedDate = data["CompletedDate"]
        ? new Date(data["CompletedDate"].toString())
        : <any>undefined;
      this.status = data["Status"];
    }
  }

  static fromJS(data: any): UpdateProjectTaskModel {
    data = typeof data === "object" ? data : {};
    let result = new UpdateProjectTaskModel();
    result.init(data);
    return result;
  }

  toJSON(data?: any) {
    data = typeof data === "object" ? data : {};
    data["Name"] = this.name;
    data["Description"] = this.description;
    data["Number"] = this.number;
    data["AssigneeId"] = this.assigneeId;
    data["DueDate"] = this.dueDate
      ? this.dueDate.toISOString()
      : <any>undefined;
    data["CompletedDate"] = this.completedDate
      ? this.completedDate.toISOString()
      : <any>undefined;
    data["Status"] = this.status;
    return data;
  }
}

export interface IUpdateProjectTaskModel {
  name: string;
  description: string;
  number: string;
  assigneeId: string;
  dueDate?: Date | undefined;
  completedDate?: Date | undefined;
  status: ProjectTaskStatus;
}

export class SwaggerException extends Error {
  message: string;
  status: number;
  response: string;
  headers: { [key: string]: any };
  result: any;

  constructor(
    message: string,
    status: number,
    response: string,
    headers: { [key: string]: any },
    result: any
  ) {
    super();

    this.message = message;
    this.status = status;
    this.response = response;
    this.headers = headers;
    this.result = result;
  }

  protected isSwaggerException = true;

  static isSwaggerException(obj: any): obj is SwaggerException {
    return obj.isSwaggerException === true;
  }
}

function throwException(
  message: string,
  status: number,
  response: string,
  headers: { [key: string]: any },
  result?: any
): Observable<any> {
  if (result !== null && result !== undefined) return Observable.throw(result);
  else
    return Observable.throw(
      new SwaggerException(message, status, response, headers, null)
    );
}

function blobToText(blob: any): Observable<string> {
  return new Observable<string>((observer: any) => {
    if (!blob) {
      observer.next("");
      observer.complete();
    } else {
      let reader = new FileReader();
      reader.onload = function() {
        observer.next(this.result);
        observer.complete();
      };
      reader.readAsText(blob);
    }
  });
}
